module LeadsHelper
  
  #values need to access the craigslist api based on this https://github.com/threetrieslater/craigler
  def us_states
      [
        ['All', 'anywhere'],
        ['Alabama', 'alabama'],
        ['Alaska', 'alaska'],
        ['Arizona', 'arizona'],
        ['Arkansas', 'arkansas'],
        ['California', 'california'],
        ['Colorado', 'colorado'],
        ['Connecticut', 'connecticut'],
        ['Delaware', 'delaware'],
        ['District of Columbia', 'dc'],
        ['Florida', 'florida'],
        ['Georgia', 'georgia'],
        ['Hawaii', 'hawaii'],
        ['Idaho', 'idaho'],
        ['Illinois', 'illinois'],
        ['Indiana', 'indiana'],
        ['Iowa', 'iowa'],
        ['Kansas', 'kansas'],
        ['Kentucky', 'kentucky'],
        ['Louisiana', 'louisiana'],
        ['Maine', 'maine'],
        ['Maryland', 'maryland'],
        ['Massachusetts', 'mass'],
        ['Michigan', 'michigan'],
        ['Minnesota', 'minnesota'],
        ['Mississippi', 'mississippi'],
        ['Missouri', 'missouri'],
        ['Montana', 'montana'],
        ['Nebraska', 'nebraska'],
        ['Nevada', 'nevada'],
        ['New Hampshire', 'n_hampshire'],
        ['New Jersey', 'new_jersey'],
        ['New Mexico', 'new_mexico'],
        ['New York', 'new_york'],
        ['North Carolina', 'n_carolina'],
        ['North Dakota', 'north_dakota'],
        ['Ohio', 'ohio'],
        ['Oklahoma', 'oklahoma'],
        ['Oregon', 'oregon'],
        ['Pennsylvania', 'pennsylvania'],
        ['Rhode Island', 'rhode_island'],
        ['South Carolina', 's_carolina'],
        ['South Dakota', 'south_dakota'],
        ['Tennessee', 'tennessee'],
        ['Texas', 'texas'],
        ['Utah', 'utah'],
        ['Vermont', 'vermont'],
        ['Virginia', 'virginia'],
        ['Washington', 'washington'],
        ['West Virginia', 'west_virginia'],
        ['Wisconsin', 'wisconsin'],
        ['Wyoming', 'wyoming']
      ]
  end
  
end
